# -*- coding: utf-8 -*-
"""VarianceThresholding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16kTUg7LakWqKF7bb5_aTg0DO5NiyD1hi
"""

import sklearn.preprocessing as sklp
import sklearn.feature_selection as feat
import pandas as pd

def variance_threshold(df, threshold):
  '''
  Does Variance Thresholding feature selection on data
  Assumes df is not yet normalized and is in the same
  format as ALL_DB_COL_data_100_threshold.csv read into
  pandas dataframe
  '''
  #Transpose, Getting Rid of non feature rows, converting to float to make sure
  #df.transpose()
  df = df.transpose()
  df = df.drop('Country', 0)
  df = df.drop('Series', 0)
  df = df.drop('COUNT_NAN', 0)
  df = df.drop('COUNT_TOT', 0)
  df = df.drop('COVERAGE_PERCENT', 0)
  df = df.drop('True', 0)
  df = df.astype('float64', errors = 'ignore')

  #normalize from 0 to 1, then variance threshold
  scaler = sklp.MinMaxScaler()
  selector = feat.VarianceThreshold(threshold)

  scaled = scaler.fit_transform(df)
  selected = selector.fit_transform(scaled)
  return selected